/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listware;

import framework.Input;
import framework.Record;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author truep
 */
public class FormPreviewInput extends javax.swing.JDialog {

    /**
     * Creates new form FormPreviewInput2
     */
    public FormPreviewInput(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FormPreviewInput(java.awt.Frame parent, boolean modal, String filePath, String delimiter, String qualifier ) {
        super(parent, modal);
        try {
            initComponents();
            Input input = new Input(filePath, delimiter, qualifier);
            int k = 0;
            
            Record[] records = input.getRecordsForPreview();
            String[][] rows = new String[records.length][input.headerNames.length];
            for(int i = 0; i < records.length; i++) {
                for(int j = 0; j < input.headerNames.length; j++) {
                    rows[i][j] = records[i].get(input.headerNames[j]);
                }
            }
            
            JTable table = new JTable(rows, input.headerNames);
            JScrollPane scrollPane = new JScrollPane(table);
            this.setContentPane(scrollPane);
            input.closeReader();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormPreviewInput.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preview Input");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
